### ISSUE TITLE
AttributeError: 'economicsl.accounting.FastLedger' object has no attribute 'get_equity_value'

### ISSUE THREAD

**Issue by roguetrainer** [ox-inet-resilience/firesale_stresstest#2]
I'm not sure if this repo is being maintained?
I am getting the error: `AttributeError: 'economicsl.accounting.FastLedger' object has no attribute 'get_equity_value'`
In [https://github.com/ox-inet-resilience/py-economicsl/blob/master/economicsl/accounting.py](https://github.com/ox-inet-resilience/py-economicsl/blob/master/economicsl/accounting.py) the `FastLedger` class has a method `get_equity_valuation` but not `get_equity_value`. Could it have been renamed?
Thanks for any help with this.

**Comment by roguetrainer** [comment]
Oops. This must be my fault. I had a stale version of `constraints.py`.

**Comment by rht** [comment]
> I'm not sure if this repo is being maintained?

Hmmm the repo is still being used for illustration purpose for the full model of system-wide stress test (not yet public).

It would be great if you have feedback of the documentation of the code (if some parts are unclear, etc)!

**Comment by roguetrainer** [comment]
Thanks RHT. I'll let you know how I get on. 
I'm trying to tell if the UML diagram in [https://github.com/ox-inet-resilience/firesale_stresstest](https://github.com/ox-inet-resilience/firesale_stresstest) is current. Do you work on that too? (It is based on `economicsl`, of course.)
Do you work with Julia in your team? I was skeptical that I would like any language as close to Matlab. But the dynamic dispatch is a game changer IMHO. Plus the convenience of getting pedal-to-the-metal speed.

**Comment by rht** [comment]
Yes, I made that diagram. It is still current, I think.

> Do you work with Julia in your team?

Yes, on a climate modeling with @alissak. I definitely can vouch for the speed. Previously we had a Python version that took 4.5 hours on a 64-CPU AWS instance, and this was only 6 agents, and we need to scale more. After a conversion to Julia, the code took 36 mins on a 16-CPU AWS (7.5x speedup), and the code is not even fully parallelized yet. If nothing is parallelized, the Julia version is ~21x faster, which I intend to have the same multiplication of speed if fully parallelized. Code to reproduce: https://github.com/rht/climate_stress_test_benchmark. Discussion thread: https://discourse.julialang.org/t/optim-jl-vs-scipy-optimize-once-again/61661. If you notice, the main bottleneck of the climate stress test model is on optimization vs scipy.optimize.

You can see more benchmark for more ABMs at https://juliadynamics.github.io/Agents.jl/v4.0/comparison/ (Agents.jl's API is originally based on Mesa, but has diverged in API design since then).

(If the syntax similarity to MATLAB is off putting, maybe you can think of Julia's syntax to be similar to Ruby instead? ;))
